[2021-04-24 11:39:51,160] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,431] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,432] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,432] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:39:51,432] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,770] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-09-01T00:00:00+00:00
[2021-04-24 11:39:51,779] {standard_task_runner.py:52} INFO - Started process 107 to run task
[2021-04-24 11:39:51,791] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2019-09-01T00:00:00+00:00', '--job-id', '35', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp1qqwcq47', '--error-file', '/tmp/tmpvg0ua1vl']
[2021-04-24 11:39:51,793] {standard_task_runner.py:77} INFO - Job 35: Subtask Stage_songs
[2021-04-24 11:39:52,650] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2019-09-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:39:54,167] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-01T00:00:00+00:00
[2021-04-24 11:39:54,170] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:39:54,193] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:39:54,199] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20190901T000000, start_date=20210424T113951, end_date=20210424T113954
[2021-04-24 11:39:54,553] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:16:33,068] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,656] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,657] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:33,657] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:16:33,657] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:34,269] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-09-01T00:00:00+00:00
[2021-04-27 20:16:34,857] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2019-09-01T00:00:00+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmponh3zw3p', '--error-file', '/tmp/tmpi9whncz1']
[2021-04-27 20:16:34,858] {standard_task_runner.py:77} INFO - Job 43: Subtask Stage_songs
[2021-04-27 20:16:34,563] {standard_task_runner.py:52} INFO - Started process 129 to run task
[2021-04-27 20:16:37,338] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2019-09-01T00:00:00+00:00 [running]> on host 88b3af0c26c0
[2021-04-27 20:16:40,184] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-01T00:00:00+00:00
[2021-04-27 20:16:40,185] {stage_redshift.py:65} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:16:40,186] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 66, in execute
    s3 = S3Hook(aws_conn_id=self.aws_credentials_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'aws_credentials_id'
[2021-04-27 20:16:40,278] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20190901T000000, start_date=20210427T201633, end_date=20210427T201640
[2021-04-27 20:16:41,533] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:33:37,166] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:38,045] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:38,059] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:38,063] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:33:38,065] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:38,509] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-09-01T00:00:00+00:00
[2021-04-27 20:33:38,825] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2019-09-01T00:00:00+00:00', '--job-id', '31', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpu0czbvzo', '--error-file', '/tmp/tmpqd7208jl']
[2021-04-27 20:33:38,743] {standard_task_runner.py:52} INFO - Started process 108 to run task
[2021-04-27 20:33:38,845] {standard_task_runner.py:77} INFO - Job 31: Subtask Stage_songs
[2021-04-27 20:33:41,594] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2019-09-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:33:43,668] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-01T00:00:00+00:00
[2021-04-27 20:33:43,681] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:33:43,686] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:33:44,095] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:33:45,585] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-27 20:33:46,028] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:33:46,370] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:33:49,478] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:33:49,569] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20190901T000000, start_date=20210427T203337, end_date=20210427T203349
[2021-04-27 20:33:51,295] {local_task_job.py:188} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2021-04-27 20:33:51,525] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 108
[2021-04-27 20:33:51,525] {process_utils.py:66} INFO - Process psutil.Process(pid=108, status='terminated', exitcode=1, started='20:33:38') (108) terminated with exit code 1
