[2021-04-24 11:39:51,067] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,454] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,454] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,455] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:39:51,455] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,861] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-02-01T00:00:00+00:00
[2021-04-24 11:39:51,991] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-02-01T00:00:00+00:00', '--job-id', '32', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpv4syx9sw', '--error-file', '/tmp/tmpg1rejl1m']
[2021-04-24 11:39:51,992] {standard_task_runner.py:77} INFO - Job 32: Subtask Stage_songs
[2021-04-24 11:39:51,933] {standard_task_runner.py:52} INFO - Started process 113 to run task
[2021-04-24 11:39:52,334] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:39:53,868] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-01T00:00:00+00:00
[2021-04-24 11:39:53,872] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:39:53,940] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:39:53,976] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200201T000000, start_date=20210424T113951, end_date=20210424T113953
[2021-04-24 11:39:54,555] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 09:07:55,737] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [queued]>
[2021-04-26 09:07:57,581] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [queued]>
[2021-04-26 09:07:57,581] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:07:57,581] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 09:07:57,581] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:07:58,133] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-02-01T00:00:00+00:00
[2021-04-26 09:07:58,372] {standard_task_runner.py:52} INFO - Started process 86 to run task
[2021-04-26 09:07:58,540] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-02-01T00:00:00+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpyew2v0wv', '--error-file', '/tmp/tmpnd2jvysj']
[2021-04-26 09:07:58,664] {standard_task_runner.py:77} INFO - Job 18: Subtask Stage_songs
[2021-04-26 09:08:02,590] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [running]> on host b5c40a6f08c7
[2021-04-26 09:08:05,956] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-01T00:00:00+00:00
[2021-04-26 09:08:06,064] {stage_redshift.py:63} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 09:08:06,065] {stage_redshift.py:68} INFO - Preparing destination Redshift table
[2021-04-26 09:08:06,729] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:09,396] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-26 09:08:10,032] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 09:08:10,436] {stage_redshift.py:71} INFO - Getting data from S3 to Redshift
[2021-04-26 09:08:10,744] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:12,206] {dbapi.py:180} INFO - Running statement: 
             COPY staging_songs 
             FROM 's3://udacity-dend/song_data/*/*/*/'
             FORMAT AS JSON 'JSON 'auto''
             CREDENTIALS
             'aws_access_key_id=None;aws_secret_access_key=None'
                , parameters: None
[2021-04-26 09:08:12,779] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 81, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "auto"
LINE 4:              FORMAT AS JSON 'JSON 'auto''
                                           ^

[2021-04-26 09:08:13,169] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200201T000000, start_date=20210426T090756, end_date=20210426T090813
[2021-04-26 09:08:15,026] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:16:32,936] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,458] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,459] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:33,459] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:16:33,459] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:33,875] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-02-01T00:00:00+00:00
[2021-04-27 20:16:34,374] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-02-01T00:00:00+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpzp8k93ut', '--error-file', '/tmp/tmp6lqg88l6']
[2021-04-27 20:16:34,144] {standard_task_runner.py:52} INFO - Started process 127 to run task
[2021-04-27 20:16:34,500] {standard_task_runner.py:77} INFO - Job 44: Subtask Stage_songs
[2021-04-27 20:16:37,240] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [running]> on host 88b3af0c26c0
[2021-04-27 20:16:40,089] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-01T00:00:00+00:00
[2021-04-27 20:16:40,120] {stage_redshift.py:65} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:16:40,120] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 66, in execute
    s3 = S3Hook(aws_conn_id=self.aws_credentials_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'aws_credentials_id'
[2021-04-27 20:16:40,140] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200201T000000, start_date=20210427T201633, end_date=20210427T201640
[2021-04-27 20:16:41,127] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:33:53,794] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:54,149] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:54,153] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:54,158] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:33:54,164] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:54,571] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-02-01T00:00:00+00:00
[2021-04-27 20:33:54,847] {standard_task_runner.py:52} INFO - Started process 121 to run task
[2021-04-27 20:33:55,189] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-02-01T00:00:00+00:00', '--job-id', '40', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp7bd9_4nj', '--error-file', '/tmp/tmpydgtcyun']
[2021-04-27 20:33:55,190] {standard_task_runner.py:77} INFO - Job 40: Subtask Stage_songs
[2021-04-27 20:33:57,386] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-02-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:33:59,528] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-01T00:00:00+00:00
[2021-04-27 20:33:59,568] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:33:59,608] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:33:59,752] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:34:01,271] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-27 20:34:02,528] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:34:02,853] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:34:05,495] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:34:05,500] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200201T000000, start_date=20210427T203353, end_date=20210427T203405
[2021-04-27 20:34:06,070] {local_task_job.py:146} INFO - Task exited with return code 1
