[2021-04-24 11:40:02,559] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-04-01T00:00:00+00:00 [queued]>
[2021-04-24 11:40:02,766] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-04-01T00:00:00+00:00 [queued]>
[2021-04-24 11:40:02,768] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:40:02,770] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:40:02,771] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:40:02,936] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-04-01T00:00:00+00:00
[2021-04-24 11:40:02,998] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-04-01T00:00:00+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp39qeglti', '--error-file', '/tmp/tmph2_1bw2t']
[2021-04-24 11:40:03,000] {standard_task_runner.py:77} INFO - Job 43: Subtask Stage_songs
[2021-04-24 11:40:02,948] {standard_task_runner.py:52} INFO - Started process 129 to run task
[2021-04-24 11:40:03,544] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-04-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:40:04,000] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-01T00:00:00+00:00
[2021-04-24 11:40:04,003] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:40:04,097] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:40:04,140] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200401T000000, start_date=20210424T114002, end_date=20210424T114004
[2021-04-24 11:40:04,497] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:15:54,527] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-04-01T00:00:00+00:00 [queued]>
[2021-04-27 20:15:55,117] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-04-01T00:00:00+00:00 [queued]>
[2021-04-27 20:15:55,117] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:15:55,117] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:15:55,118] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:15:55,649] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-04-01T00:00:00+00:00
[2021-04-27 20:15:56,008] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-04-01T00:00:00+00:00', '--job-id', '23', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpuzx6wc_o', '--error-file', '/tmp/tmplmj0hs0_']
[2021-04-27 20:15:56,009] {standard_task_runner.py:77} INFO - Job 23: Subtask Stage_songs
[2021-04-27 20:15:55,926] {standard_task_runner.py:52} INFO - Started process 93 to run task
[2021-04-27 20:15:58,731] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-04-01T00:00:00+00:00 [running]> on host 88b3af0c26c0
[2021-04-27 20:16:00,790] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-01T00:00:00+00:00
[2021-04-27 20:16:00,791] {stage_redshift.py:65} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:16:00,794] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 66, in execute
    s3 = S3Hook(aws_conn_id=self.aws_credentials_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'aws_credentials_id'
[2021-04-27 20:16:01,084] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200401T000000, start_date=20210427T201554, end_date=20210427T201601
[2021-04-27 20:16:01,853] {local_task_job.py:188} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2021-04-27 20:16:02,120] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 93
[2021-04-27 20:16:02,196] {process_utils.py:66} INFO - Process psutil.Process(pid=93, status='terminated', exitcode=1, started='20:15:55') (93) terminated with exit code 1
[2021-04-27 20:34:03,401] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-04-01T00:00:00+00:00 [queued]>
[2021-04-27 20:34:03,725] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-04-01T00:00:00+00:00 [queued]>
[2021-04-27 20:34:03,725] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:34:03,726] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:34:03,726] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:34:04,097] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-04-01T00:00:00+00:00
[2021-04-27 20:34:04,405] {standard_task_runner.py:52} INFO - Started process 125 to run task
[2021-04-27 20:34:04,586] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-04-01T00:00:00+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmph81llcm2', '--error-file', '/tmp/tmpza82gfs0']
[2021-04-27 20:34:04,586] {standard_task_runner.py:77} INFO - Job 44: Subtask Stage_songs
[2021-04-27 20:34:05,621] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-04-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:34:07,113] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-01T00:00:00+00:00
[2021-04-27 20:34:07,114] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:34:07,114] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:34:07,787] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:34:09,404] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-27 20:34:09,854] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:34:10,174] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:34:12,213] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:34:12,227] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200401T000000, start_date=20210427T203403, end_date=20210427T203412
[2021-04-27 20:34:12,460] {local_task_job.py:146} INFO - Task exited with return code 1
