[2021-04-24 11:46:09,408] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [queued]>
[2021-04-24 11:46:09,564] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [queued]>
[2021-04-24 11:46:09,564] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:46:09,564] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:46:09,564] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:46:09,725] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2021-03-01T00:00:00+00:00
[2021-04-24 11:46:09,759] {standard_task_runner.py:52} INFO - Started process 255 to run task
[2021-04-24 11:46:09,811] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2021-03-01T00:00:00+00:00', '--job-id', '109', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpw405208t', '--error-file', '/tmp/tmps0vqh682']
[2021-04-24 11:46:09,811] {standard_task_runner.py:77} INFO - Job 109: Subtask Stage_events
[2021-04-24 11:46:10,179] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:46:10,362] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2021-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-01T00:00:00+00:00
[2021-04-24 11:46:10,364] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:46:10,430] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:46:10,446] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20210301T000000, start_date=20210424T114609, end_date=20210424T114610
[2021-04-24 11:46:10,625] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 09:08:43,940] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [queued]>
[2021-04-26 09:08:45,213] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [queued]>
[2021-04-26 09:08:45,219] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:08:45,220] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 09:08:45,222] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:08:45,668] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2021-03-01T00:00:00+00:00
[2021-04-26 09:08:46,010] {standard_task_runner.py:52} INFO - Started process 117 to run task
[2021-04-26 09:08:46,205] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2021-03-01T00:00:00+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp9d3999is', '--error-file', '/tmp/tmp_frwv1k3']
[2021-04-26 09:08:46,206] {standard_task_runner.py:77} INFO - Job 36: Subtask Stage_events
[2021-04-26 09:08:47,486] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [running]> on host b5c40a6f08c7
[2021-04-26 09:08:48,336] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2021-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-01T00:00:00+00:00
[2021-04-26 09:08:48,337] {stage_redshift.py:63} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 09:08:48,338] {stage_redshift.py:68} INFO - Preparing destination Redshift table
[2021-04-26 09:08:48,514] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:50,091] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_events, parameters: None
[2021-04-26 09:08:50,537] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 09:08:50,842] {stage_redshift.py:71} INFO - Getting data from S3 to Redshift
[2021-04-26 09:08:50,914] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:52,344] {dbapi.py:180} INFO - Running statement: 
             COPY staging_events 
             FROM 's3://udacity-dend/log_data/2018/11/*'
             FORMAT AS JSON 'log_json_path.json'
             CREDENTIALS
             'aws_access_key_id=None;aws_secret_access_key=None'
                , parameters: None
[2021-04-26 09:08:52,894] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 81, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: S3ServiceException:The AWS Access Key Id you provided does not exist in our records.,Status 403,Error InvalidAccessKeyId,Rid AFQ8P63YH3ENYT3Q,ExtRid AHFpMlJ9EtKgFYzWwlyhiy5ka2Kz1Wt2Y0tSu9//1sown+6rtgcn4FNFxdaHnRI3xK8zzk3rk5w=,CanRetry 1
DETAIL:  
  -----------------------------------------------
  error:  S3ServiceException:The AWS Access Key Id you provided does not exist in our records.,Status 403,Error InvalidAccessKeyId,Rid AFQ8P63YH3ENYT3Q,ExtRid AHFpMlJ9EtKgFYzWwlyhiy5ka2Kz1Wt2Y0tSu9//1sown+6rtgcn4FNFxdaHnRI3xK8zzk3rk5w=,CanRetry 1
  code:      8001
  context:   Listing bucket=udacity-dend prefix=log_data/2018/11/*
  query:     245
  location:  s3_utility.cpp:654
  process:   padbmaster [pid=13912]
  -----------------------------------------------


[2021-04-26 09:08:52,936] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20210301T000000, start_date=20210426T090844, end_date=20210426T090852
[2021-04-26 09:08:53,647] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 12:37:15,543] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [queued]>
[2021-04-26 12:37:15,855] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [queued]>
[2021-04-26 12:37:15,855] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:37:15,870] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 12:37:15,871] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:37:16,012] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2021-03-01T00:00:00+00:00
[2021-04-26 12:37:16,029] {standard_task_runner.py:52} INFO - Started process 122 to run task
[2021-04-26 12:37:16,065] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2021-03-01T00:00:00+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp7qzzy8k7', '--error-file', '/tmp/tmp4gpvp6x6']
[2021-04-26 12:37:16,066] {standard_task_runner.py:77} INFO - Job 36: Subtask Stage_events
[2021-04-26 12:37:16,415] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [running]> on host 0f1e1da1f4f6
[2021-04-26 12:37:17,452] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2021-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-01T00:00:00+00:00
[2021-04-26 12:37:17,633] {stage_redshift.py:62} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 12:37:17,633] {stage_redshift.py:67} INFO - Preparing destination Redshift table
[2021-04-26 12:37:17,797] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:37:21,236] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_events, parameters: None
[2021-04-26 12:37:21,674] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 12:37:21,990] {stage_redshift.py:70} INFO - Getting data from S3 to Redshift
[2021-04-26 12:37:22,019] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:37:24,241] {dbapi.py:180} INFO - Running statement: 
             COPY staging_events 
             FROM '/offor_data/log_data/2018/11/*'
             FORMAT AS JSON 'log_json_path.json'
                  , parameters: None
[2021-04-26 12:37:24,679] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 80, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: LOAD source is not supported. (Hint: only S3 or DynamoDB or EMR based load is allowed)

[2021-04-26 12:37:24,717] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20210301T000000, start_date=20210426T123715, end_date=20210426T123724
[2021-04-26 12:37:24,971] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:40:36,046] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:40:36,320] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:40:36,321] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:40:36,321] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:40:36,321] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:40:36,481] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2021-03-01T00:00:00+00:00
[2021-04-27 20:40:36,543] {standard_task_runner.py:52} INFO - Started process 256 to run task
[2021-04-27 20:40:36,579] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2021-03-01T00:00:00+00:00', '--job-id', '111', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpadpqkt2d', '--error-file', '/tmp/tmpc7okopts']
[2021-04-27 20:40:36,585] {standard_task_runner.py:77} INFO - Job 111: Subtask Stage_events
[2021-04-27 20:40:37,094] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2021-03-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:40:37,347] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2021-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-01T00:00:00+00:00
[2021-04-27 20:40:37,348] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:40:37,350] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:40:37,407] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:40:38,983] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_events, parameters: None
[2021-04-27 20:40:39,428] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:40:39,736] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:40:41,602] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:40:41,616] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20210301T000000, start_date=20210427T204036, end_date=20210427T204041
[2021-04-27 20:40:42,041] {local_task_job.py:146} INFO - Task exited with return code 1
