[2021-04-24 11:40:02,943] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-03-01T00:00:00+00:00 [queued]>
[2021-04-24 11:40:03,130] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-03-01T00:00:00+00:00 [queued]>
[2021-04-24 11:40:03,131] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:40:03,131] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:40:03,131] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:40:03,406] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-03-01T00:00:00+00:00
[2021-04-24 11:40:03,496] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-03-01T00:00:00+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp56sfoia2', '--error-file', '/tmp/tmpi9h586hr']
[2021-04-24 11:40:03,448] {standard_task_runner.py:52} INFO - Started process 135 to run task
[2021-04-24 11:40:03,525] {standard_task_runner.py:77} INFO - Job 44: Subtask Stage_songs
[2021-04-24 11:40:04,128] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-03-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:40:04,861] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-01T00:00:00+00:00
[2021-04-24 11:40:04,867] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:40:04,937] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:40:04,963] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200301T000000, start_date=20210424T114002, end_date=20210424T114004
[2021-04-24 11:40:05,249] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:16:34,523] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:35,637] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:35,637] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:35,638] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:16:35,638] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:36,063] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-03-01T00:00:00+00:00
[2021-04-27 20:16:36,841] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-03-01T00:00:00+00:00', '--job-id', '48', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpnx5_vxom', '--error-file', '/tmp/tmp9b1dlt_j']
[2021-04-27 20:16:36,842] {standard_task_runner.py:77} INFO - Job 48: Subtask Stage_songs
[2021-04-27 20:16:36,590] {standard_task_runner.py:52} INFO - Started process 134 to run task
[2021-04-27 20:16:39,851] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-03-01T00:00:00+00:00 [running]> on host 88b3af0c26c0
[2021-04-27 20:16:42,563] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-01T00:00:00+00:00
[2021-04-27 20:16:42,576] {stage_redshift.py:65} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:16:42,595] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 66, in execute
    s3 = S3Hook(aws_conn_id=self.aws_credentials_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'aws_credentials_id'
[2021-04-27 20:16:42,725] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200301T000000, start_date=20210427T201634, end_date=20210427T201642
[2021-04-27 20:16:43,387] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:33:59,745] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:34:00,029] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2020-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:34:00,030] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:34:00,031] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:34:00,031] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:34:00,568] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2020-03-01T00:00:00+00:00
[2021-04-27 20:34:01,247] {standard_task_runner.py:52} INFO - Started process 124 to run task
[2021-04-27 20:34:01,738] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2020-03-01T00:00:00+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpv6l530fw', '--error-file', '/tmp/tmptim6z9e4']
[2021-04-27 20:34:01,757] {standard_task_runner.py:77} INFO - Job 43: Subtask Stage_songs
[2021-04-27 20:34:03,013] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2020-03-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:34:03,969] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2020-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-01T00:00:00+00:00
[2021-04-27 20:34:03,974] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:34:04,006] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:34:04,399] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:34:05,969] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-27 20:34:06,412] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:34:06,698] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:34:10,499] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:34:10,537] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20200301T000000, start_date=20210427T203359, end_date=20210427T203410
[2021-04-27 20:34:10,837] {local_task_job.py:146} INFO - Task exited with return code 1
