[2021-04-24 11:39:51,214] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,469] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,471] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,472] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:39:51,472] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,818] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-09-01T00:00:00+00:00
[2021-04-24 11:39:51,852] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2021-04-24 11:39:51,972] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-09-01T00:00:00+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpzhdr5o9s', '--error-file', '/tmp/tmpo3ihc1gs']
[2021-04-24 11:39:52,065] {standard_task_runner.py:77} INFO - Job 38: Subtask Stage_events
[2021-04-24 11:39:53,071] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-09-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:39:54,641] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-01T00:00:00+00:00
[2021-04-24 11:39:54,645] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:39:54,837] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:39:54,891] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190901T000000, start_date=20210424T113951, end_date=20210424T113954
[2021-04-24 11:39:55,972] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:16:32,583] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,377] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,377] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:33,377] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:16:33,378] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:33,768] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-09-01T00:00:00+00:00
[2021-04-27 20:16:34,178] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-09-01T00:00:00+00:00', '--job-id', '40', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp8w51toow', '--error-file', '/tmp/tmpton86zhp']
[2021-04-27 20:16:34,377] {standard_task_runner.py:77} INFO - Job 40: Subtask Stage_events
[2021-04-27 20:16:34,010] {standard_task_runner.py:52} INFO - Started process 126 to run task
[2021-04-27 20:16:36,687] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-09-01T00:00:00+00:00 [running]> on host 88b3af0c26c0
[2021-04-27 20:16:39,694] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-01T00:00:00+00:00
[2021-04-27 20:16:39,700] {stage_redshift.py:65} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:16:39,702] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 66, in execute
    s3 = S3Hook(aws_conn_id=self.aws_credentials_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'aws_credentials_id'
[2021-04-27 20:16:39,797] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190901T000000, start_date=20210427T201632, end_date=20210427T201639
[2021-04-27 20:16:40,852] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:33:35,461] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:36,075] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-09-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:36,077] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:36,078] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:33:36,080] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:36,438] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-09-01T00:00:00+00:00
[2021-04-27 20:33:36,952] {standard_task_runner.py:52} INFO - Started process 107 to run task
[2021-04-27 20:33:37,358] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-09-01T00:00:00+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpsdr2w4mq', '--error-file', '/tmp/tmp03p29gr3']
[2021-04-27 20:33:37,360] {standard_task_runner.py:77} INFO - Job 30: Subtask Stage_events
[2021-04-27 20:33:38,823] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-09-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:33:41,498] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-09-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-01T00:00:00+00:00
[2021-04-27 20:33:41,537] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:33:41,557] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:33:41,765] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:33:43,283] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_events, parameters: None
[2021-04-27 20:33:43,742] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:33:44,036] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:33:48,607] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:33:48,812] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190901T000000, start_date=20210427T203335, end_date=20210427T203348
[2021-04-27 20:33:50,638] {local_task_job.py:146} INFO - Task exited with return code 1
