[2021-04-24 11:38:56,363] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-07-01T00:00:00+00:00 [queued]>
[2021-04-24 11:38:56,882] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-07-01T00:00:00+00:00 [queued]>
[2021-04-24 11:38:56,893] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:38:56,900] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:38:56,904] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:38:58,242] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-07-01T00:00:00+00:00
[2021-04-24 11:38:58,325] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-07-01T00:00:00+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp3biovoqb', '--error-file', '/tmp/tmpu91lg3jr']
[2021-04-24 11:38:58,309] {standard_task_runner.py:52} INFO - Started process 90 to run task
[2021-04-24 11:38:58,712] {standard_task_runner.py:77} INFO - Job 26: Subtask Stage_events
[2021-04-24 11:39:00,714] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-07-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:39:02,383] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-01T00:00:00+00:00
[2021-04-24 11:39:02,384] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:39:02,429] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:39:02,811] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190701T000000, start_date=20210424T113856, end_date=20210424T113902
[2021-04-24 11:39:05,753] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:16:32,893] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-07-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,547] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-07-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,580] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:33,580] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:16:33,580] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:34,240] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-07-01T00:00:00+00:00
[2021-04-27 20:16:35,270] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-07-01T00:00:00+00:00', '--job-id', '42', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpgetzokpr', '--error-file', '/tmp/tmp1ou3jk9b']
[2021-04-27 20:16:35,363] {standard_task_runner.py:77} INFO - Job 42: Subtask Stage_events
[2021-04-27 20:16:34,825] {standard_task_runner.py:52} INFO - Started process 130 to run task
[2021-04-27 20:16:37,706] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-07-01T00:00:00+00:00 [running]> on host 88b3af0c26c0
[2021-04-27 20:16:40,656] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-01T00:00:00+00:00
[2021-04-27 20:16:40,663] {stage_redshift.py:65} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:16:40,665] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 66, in execute
    s3 = S3Hook(aws_conn_id=self.aws_credentials_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'aws_credentials_id'
[2021-04-27 20:16:40,677] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190701T000000, start_date=20210427T201633, end_date=20210427T201640
[2021-04-27 20:16:42,413] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:33:02,741] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-07-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:03,537] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-07-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:03,537] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:03,537] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:33:03,537] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:05,389] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-07-01T00:00:00+00:00
[2021-04-27 20:33:05,643] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-07-01T00:00:00+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp9imw0txa', '--error-file', '/tmp/tmp4ffoy82g']
[2021-04-27 20:33:05,676] {standard_task_runner.py:77} INFO - Job 21: Subtask Stage_events
[2021-04-27 20:33:05,607] {standard_task_runner.py:52} INFO - Started process 83 to run task
[2021-04-27 20:33:08,547] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-07-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:33:11,022] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-01T00:00:00+00:00
[2021-04-27 20:33:11,023] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:33:11,023] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:33:11,428] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:33:13,081] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_events, parameters: None
[2021-04-27 20:33:13,583] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:33:13,901] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:33:17,452] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:33:17,479] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190701T000000, start_date=20210427T203302, end_date=20210427T203317
[2021-04-27 20:33:19,356] {local_task_job.py:146} INFO - Task exited with return code 1
