[2021-04-24 10:53:07,725] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [queued]>
[2021-04-24 10:53:07,824] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [queued]>
[2021-04-24 10:53:07,824] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 10:53:07,825] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 10:53:07,825] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 10:53:07,983] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-03-01T00:00:00+00:00
[2021-04-24 10:53:07,995] {standard_task_runner.py:52} INFO - Started process 75 to run task
[2021-04-24 10:53:08,012] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-03-01T00:00:00+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmphqphap0p', '--error-file', '/tmp/tmp9iq7der1']
[2021-04-24 10:53:08,054] {standard_task_runner.py:77} INFO - Job 18: Subtask Stage_events
[2021-04-24 10:53:08,315] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [running]> on host 53be67297d88
[2021-04-24 10:53:08,606] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2021-04-24 10:53:08,609] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 10:53:08,662] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 10:53:08,667] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190301T000000, start_date=20210424T105307, end_date=20210424T105308
[2021-04-24 10:53:08,873] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-24 11:38:56,364] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [queued]>
[2021-04-24 11:38:56,886] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [queued]>
[2021-04-24 11:38:56,892] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:38:56,902] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:38:56,903] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:38:57,602] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-03-01T00:00:00+00:00
[2021-04-24 11:38:57,618] {standard_task_runner.py:52} INFO - Started process 89 to run task
[2021-04-24 11:38:57,632] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-03-01T00:00:00+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpi5uy88zz', '--error-file', '/tmp/tmpcjyqeign']
[2021-04-24 11:38:57,633] {standard_task_runner.py:77} INFO - Job 27: Subtask Stage_events
[2021-04-24 11:38:59,424] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:39:00,886] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2021-04-24 11:39:01,020] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:39:01,702] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:39:03,045] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190301T000000, start_date=20210424T113856, end_date=20210424T113902
[2021-04-24 11:39:06,347] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:16:31,074] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:31,833] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:31,860] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:31,871] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:16:31,875] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:32,233] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-03-01T00:00:00+00:00
[2021-04-27 20:16:32,509] {standard_task_runner.py:52} INFO - Started process 123 to run task
[2021-04-27 20:16:32,772] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-03-01T00:00:00+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpz5fri68z', '--error-file', '/tmp/tmp6i539rfl']
[2021-04-27 20:16:32,860] {standard_task_runner.py:77} INFO - Job 38: Subtask Stage_events
[2021-04-27 20:16:34,738] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [running]> on host 88b3af0c26c0
[2021-04-27 20:16:37,285] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2021-04-27 20:16:37,286] {stage_redshift.py:65} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:16:37,286] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 66, in execute
    s3 = S3Hook(aws_conn_id=self.aws_credentials_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'aws_credentials_id'
[2021-04-27 20:16:37,354] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190301T000000, start_date=20210427T201631, end_date=20210427T201637
[2021-04-27 20:16:39,241] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:37:47,056] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:37:47,119] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [queued]>
[2021-04-27 20:37:47,119] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:37:47,119] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:37:47,119] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:37:47,180] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2019-03-01T00:00:00+00:00
[2021-04-27 20:37:47,191] {standard_task_runner.py:52} INFO - Started process 139 to run task
[2021-04-27 20:37:47,219] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2019-03-01T00:00:00+00:00', '--job-id', '52', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpphzc8mus', '--error-file', '/tmp/tmpppdwyzk4']
[2021-04-27 20:37:47,224] {standard_task_runner.py:77} INFO - Job 52: Subtask Stage_events
[2021-04-27 20:37:47,431] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2019-03-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:37:47,658] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2021-04-27 20:37:47,659] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:37:47,671] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:37:47,774] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:37:49,230] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_events, parameters: None
[2021-04-27 20:37:49,665] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:37:49,957] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:37:51,813] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:37:51,825] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20190301T000000, start_date=20210427T203747, end_date=20210427T203751
[2021-04-27 20:37:52,090] {local_task_job.py:146} INFO - Task exited with return code 1
