[2021-04-24 11:45:28,368] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [queued]>
[2021-04-24 11:45:29,135] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [queued]>
[2021-04-24 11:45:29,213] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:45:29,229] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:45:29,252] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:45:30,068] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2020-06-01T00:00:00+00:00
[2021-04-24 11:45:30,330] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2020-06-01T00:00:00+00:00', '--job-id', '90', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp2l79423b', '--error-file', '/tmp/tmpcwtvtdwl']
[2021-04-24 11:45:30,331] {standard_task_runner.py:77} INFO - Job 90: Subtask Stage_events
[2021-04-24 11:45:30,163] {standard_task_runner.py:52} INFO - Started process 221 to run task
[2021-04-24 11:45:32,490] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:45:34,785] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2020-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-01T00:00:00+00:00
[2021-04-24 11:45:34,786] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:45:34,991] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:45:34,996] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20200601T000000, start_date=20210424T114528, end_date=20210424T114534
[2021-04-24 11:45:35,946] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 09:07:51,758] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [queued]>
[2021-04-26 09:07:53,179] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [queued]>
[2021-04-26 09:07:53,179] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:07:53,180] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 09:07:53,180] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 09:07:53,671] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2020-06-01T00:00:00+00:00
[2021-04-26 09:07:53,754] {standard_task_runner.py:52} INFO - Started process 84 to run task
[2021-04-26 09:07:53,958] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2020-06-01T00:00:00+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpjj1iorts', '--error-file', '/tmp/tmpvpmmiiot']
[2021-04-26 09:07:54,215] {standard_task_runner.py:77} INFO - Job 17: Subtask Stage_events
[2021-04-26 09:07:56,365] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [running]> on host b5c40a6f08c7
[2021-04-26 09:07:58,764] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2020-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-01T00:00:00+00:00
[2021-04-26 09:07:58,790] {stage_redshift.py:63} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 09:07:58,790] {stage_redshift.py:68} INFO - Preparing destination Redshift table
[2021-04-26 09:07:59,233] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:00,844] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_events, parameters: None
[2021-04-26 09:08:01,530] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 09:08:02,041] {stage_redshift.py:71} INFO - Getting data from S3 to Redshift
[2021-04-26 09:08:02,555] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 09:08:04,015] {dbapi.py:180} INFO - Running statement: 
             COPY staging_events 
             FROM 's3://udacity-dend/log_data/2018/11/*'
             FORMAT AS JSON 'log_json_path.json'
             CREDENTIALS
             'aws_access_key_id=None;aws_secret_access_key=None'
                , parameters: None
[2021-04-26 09:08:04,556] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 81, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: S3ServiceException:The AWS Access Key Id you provided does not exist in our records.,Status 403,Error InvalidAccessKeyId,Rid VYMQNCM45TZK8W3T,ExtRid lQNaAVzaa1TYzAjuI3hDVllcVhQlAbJ8aad1PVc6/8C/zzrb8PUIbe2wLL6b/hKwuXGJkT6D6PY=,CanRetry 1
DETAIL:  
  -----------------------------------------------
  error:  S3ServiceException:The AWS Access Key Id you provided does not exist in our records.,Status 403,Error InvalidAccessKeyId,Rid VYMQNCM45TZK8W3T,ExtRid lQNaAVzaa1TYzAjuI3hDVllcVhQlAbJ8aad1PVc6/8C/zzrb8PUIbe2wLL6b/hKwuXGJkT6D6PY=,CanRetry 1
  code:      8001
  context:   Listing bucket=udacity-dend prefix=log_data/2018/11/*
  query:     197
  location:  s3_utility.cpp:654
  process:   padbmaster [pid=13811]
  -----------------------------------------------


[2021-04-26 09:08:04,617] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20200601T000000, start_date=20210426T090751, end_date=20210426T090804
[2021-04-26 09:08:05,512] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-26 12:34:58,724] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [queued]>
[2021-04-26 12:34:58,904] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [queued]>
[2021-04-26 12:34:58,904] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:34:58,905] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-26 12:34:58,905] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-26 12:34:58,981] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2020-06-01T00:00:00+00:00
[2021-04-26 12:34:58,993] {standard_task_runner.py:52} INFO - Started process 67 to run task
[2021-04-26 12:34:59,023] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2020-06-01T00:00:00+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpcjxu2d5o', '--error-file', '/tmp/tmp50z02zr5']
[2021-04-26 12:34:59,053] {standard_task_runner.py:77} INFO - Job 8: Subtask Stage_events
[2021-04-26 12:34:59,686] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [running]> on host 0f1e1da1f4f6
[2021-04-26 12:35:00,221] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2020-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-01T00:00:00+00:00
[2021-04-26 12:35:00,222] {stage_redshift.py:62} INFO - Start implementation of StageToRedshiftOperator
[2021-04-26 12:35:00,222] {stage_redshift.py:67} INFO - Preparing destination Redshift table
[2021-04-26 12:35:00,292] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:35:01,727] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_events, parameters: None
[2021-04-26 12:35:02,655] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-26 12:35:03,055] {stage_redshift.py:70} INFO - Getting data from S3 to Redshift
[2021-04-26 12:35:03,100] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-26 12:35:04,499] {dbapi.py:180} INFO - Running statement: 
             COPY staging_events 
             FROM '/offor_data/log_data/2018/11/*'
             FORMAT AS JSON 'log_json_path.json'
                  , parameters: None
[2021-04-26 12:35:04,898] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 80, in execute
    redshift.run(execution_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: LOAD source is not supported. (Hint: only S3 or DynamoDB or EMR based load is allowed)

[2021-04-26 12:35:04,913] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20200601T000000, start_date=20210426T123458, end_date=20210426T123504
[2021-04-26 12:35:05,055] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:39:04,251] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [queued]>
[2021-04-27 20:39:04,768] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [queued]>
[2021-04-27 20:39:04,780] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:39:04,781] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:39:04,783] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:39:05,341] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2020-06-01T00:00:00+00:00
[2021-04-27 20:39:05,626] {standard_task_runner.py:52} INFO - Started process 184 to run task
[2021-04-27 20:39:05,764] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_events', '2020-06-01T00:00:00+00:00', '--job-id', '71', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpi13d8lsp', '--error-file', '/tmp/tmpkde8d55h']
[2021-04-27 20:39:05,785] {standard_task_runner.py:77} INFO - Job 71: Subtask Stage_events
[2021-04-27 20:39:08,162] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_events 2020-06-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:39:11,311] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_events
AIRFLOW_CTX_EXECUTION_DATE=2020-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-01T00:00:00+00:00
[2021-04-27 20:39:11,391] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:39:11,391] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:39:11,972] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:39:13,537] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_events, parameters: None
[2021-04-27 20:39:14,001] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:39:14,305] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:39:17,776] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:39:17,789] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_events, execution_date=20200601T000000, start_date=20210427T203904, end_date=20210427T203917
[2021-04-27 20:39:19,392] {local_task_job.py:146} INFO - Task exited with return code 1
