[2021-04-24 11:39:51,071] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-12-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,439] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-12-01T00:00:00+00:00 [queued]>
[2021-04-24 11:39:51,439] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,439] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-24 11:39:51,440] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-24 11:39:51,865] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-12-01T00:00:00+00:00
[2021-04-24 11:39:51,909] {standard_task_runner.py:52} INFO - Started process 116 to run task
[2021-04-24 11:39:52,121] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2019-12-01T00:00:00+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpn7nmn379', '--error-file', '/tmp/tmp7wv3n2nb']
[2021-04-24 11:39:52,138] {standard_task_runner.py:77} INFO - Job 34: Subtask Stage_songs
[2021-04-24 11:39:53,419] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2019-12-01T00:00:00+00:00 [running]> on host 88dcd2a12842
[2021-04-24 11:39:54,628] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernest@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-12-01T00:00:00+00:00
[2021-04-24 11:39:54,629] {stage_redshift.py:38} INFO - Start implementation of StageToRedshiftOperator
[2021-04-24 11:39:54,825] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 39, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/hooks/aws_hook.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 360, in __init__
    raise AirflowException('Either client_type or resource_type must be provided.')
airflow.exceptions.AirflowException: Either client_type or resource_type must be provided.
[2021-04-24 11:39:54,848] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20191201T000000, start_date=20210424T113951, end_date=20210424T113954
[2021-04-24 11:39:55,969] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-27 20:16:32,894] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-12-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,504] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-12-01T00:00:00+00:00 [queued]>
[2021-04-27 20:16:33,505] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:33,505] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:16:33,505] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:16:33,961] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-12-01T00:00:00+00:00
[2021-04-27 20:16:34,319] {standard_task_runner.py:52} INFO - Started process 128 to run task
[2021-04-27 20:16:34,664] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2019-12-01T00:00:00+00:00', '--job-id', '41', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmp46bbhta6', '--error-file', '/tmp/tmpdilpc42j']
[2021-04-27 20:16:34,686] {standard_task_runner.py:77} INFO - Job 41: Subtask Stage_songs
[2021-04-27 20:16:37,335] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2019-12-01T00:00:00+00:00 [running]> on host 88b3af0c26c0
[2021-04-27 20:16:40,332] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-12-01T00:00:00+00:00
[2021-04-27 20:16:40,347] {stage_redshift.py:65} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:16:40,360] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 66, in execute
    s3 = S3Hook(aws_conn_id=self.aws_credentials_id)
AttributeError: 'StageToRedshiftOperator' object has no attribute 'aws_credentials_id'
[2021-04-27 20:16:40,411] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20191201T000000, start_date=20210427T201633, end_date=20210427T201640
[2021-04-27 20:16:41,341] {local_task_job.py:188} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2021-04-27 20:16:41,438] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 128
[2021-04-27 20:16:41,970] {process_utils.py:66} INFO - Process psutil.Process(pid=128, status='terminated', exitcode=1, started='20:16:34') (128) terminated with exit code 1
[2021-04-27 20:33:42,180] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-12-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:42,910] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: project_dag.Stage_songs 2019-12-01T00:00:00+00:00 [queued]>
[2021-04-27 20:33:42,990] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:43,028] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-04-27 20:33:43,108] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-27 20:33:43,934] {taskinstance.py:1089} INFO - Executing <Task(StageToRedshiftOperator): Stage_songs> on 2019-12-01T00:00:00+00:00
[2021-04-27 20:33:44,345] {standard_task_runner.py:52} INFO - Started process 112 to run task
[2021-04-27 20:33:44,677] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'project_dag', 'Stage_songs', '2019-12-01T00:00:00+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpaj2z0q07', '--error-file', '/tmp/tmp83369cfy']
[2021-04-27 20:33:44,765] {standard_task_runner.py:77} INFO - Job 36: Subtask Stage_songs
[2021-04-27 20:33:46,847] {logging_mixin.py:104} INFO - Running <TaskInstance: project_dag.Stage_songs 2019-12-01T00:00:00+00:00 [running]> on host 478c7ec349b0
[2021-04-27 20:33:48,363] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ernestoffor@gmail.com.com
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=project_dag
AIRFLOW_CTX_TASK_ID=Stage_songs
AIRFLOW_CTX_EXECUTION_DATE=2019-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-12-01T00:00:00+00:00
[2021-04-27 20:33:48,369] {stage_redshift.py:67} INFO - Start implementation of StageToRedshiftOperator
[2021-04-27 20:33:48,371] {stage_redshift.py:74} INFO - Preparing destination Redshift table
[2021-04-27 20:33:49,217] {base.py:78} INFO - Using connection to: id: redshift. Host: redshift.cxvwoeu3kuea.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: None
[2021-04-27 20:33:51,060] {dbapi.py:180} INFO - Running statement: DELETE FROM staging_songs, parameters: None
[2021-04-27 20:33:51,507] {dbapi.py:186} INFO - Rows affected: 0
[2021-04-27 20:33:51,903] {stage_redshift.py:77} INFO - Getting data from S3 to Redshift
[2021-04-27 20:33:55,528] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 83, in execute
    s3.get_credentials().access_key,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 478, in get_credentials
    return session.get_credentials().get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
[2021-04-27 20:33:55,545] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=project_dag, task_id=Stage_songs, execution_date=20191201T000000, start_date=20210427T203342, end_date=20210427T203355
[2021-04-27 20:33:57,579] {local_task_job.py:146} INFO - Task exited with return code 1
